version: '3'

services:
  demucs-api:
    build: .
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    environment:
      - PORT=${PORT:-8080}
      - FLASK_ENV=${FLASK_ENV:-production}
      - DEBUG=${DEBUG:-false}
      - SECRET_KEY=${SECRET_KEY:-demucs-secret-key}
      - ADMIN_TOKEN=${ADMIN_TOKEN:-admin-token-12345}
      - MAX_CONTENT_LENGTH=${MAX_CONTENT_LENGTH:-524288000}
      - FILE_RETENTION_MINUTES=${FILE_RETENTION_MINUTES:-60}
      - DEFAULT_MODEL=${DEFAULT_MODEL:-htdemucs}
    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-8080}/api/models"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 